---
- name: Download WordPress
  get_url: 
          url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/tmp/wordpress-{{ wp_version }}.tar.gz
          sha256sum="{{ wp_sha256sum }}"
          force=no

- name: Create Wordpress Version {{ wp_version }} directory
  file:
        path=/tmp/wordpress-{{ wp_version }}/
        state=directory
        mode=0755
        owner=vagrant
        group=vagrant
        force=no

- name: Extract archive
  unarchive:
            src=/tmp/wordpress-{{ wp_version }}.tar.gz
            dest=/tmp/wordpress-{{ wp_version }}/
            creates=/tmp/wordpress-{{ wp_version }}/wordpress
            copy=no

# - name: Add group "wordpress"
#   group: name=wordpress

# - name: Add user "wordpress"
#   user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Create Wordpress wp/ directory
  file:
        path="/var/www/vhosts/{{ item[0].hostname }}/public_html/{{ item[1] }}/"
        state=directory
        mode=0755
        owner=www-data
        group=www-data
        force=no
  with_nested:
        - "{{ hosts }}"
        - ['wp']

- name: Copy Wordpress {{ wp_version }} index.php installation
  command: cp -n /tmp/wordpress-{{ wp_version }}/wordpress/index.php /var/www/vhosts/{{ item.hostname }}/public_html/
  with_items:
        hosts

- name: Change location of blog header
  replace: 
        dest=/var/www/vhosts/{{ item.hostname }}/public_html/index.php
        regexp="'\/wp-blog-header"
        replace="'/wp/wp-blog-header"
  with_items:
        hosts

- name: Copy Wordpress {{ wp_version }} root files
  command: cp -n /tmp/wordpress-{{ wp_version }}/wordpress/{{ item[1] }} /var/www/vhosts/{{ item[0].hostname }}/public_html/wp
  with_nested:
        - "{{ hosts }}"
        - ['wp-activate.php',
           'wp-blog-header.php',
           'wp-comments-post.php',
           'wp-cron.php',
           'wp-links-opml.php',
           'wp-load.php',
           'wp-login.php',
           'wp-mail.php',
           'wp-settings.php',
           'wp-signup.php',
           'wp-trackback.php',
           'xmlrpc.php']

- name: Copy Wordpress {{ wp_version }} root directories
  command: cp -n -R /tmp/wordpress-{{ wp_version }}/wordpress/{{ item[1] }} /var/www/vhosts/{{ item[0].hostname }}/public_html/wp
  with_nested:
        - "{{ hosts }}"
        - ['wp-admin',
           'wp-includes']

- name: Copy Wordpress {{ wp_version }} WP Content directories
  command: cp -n -R /tmp/wordpress-{{ wp_version }}/wordpress/{{ item[1] }} /var/www/vhosts/{{ item[0].hostname }}/public_html/
  with_nested:
        - "{{ hosts }}"
        - ['wp-content']

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/vhosts/{{ item.hostname }}/public_html/
  with_items:
        hosts

- name: Change ownership of hosts directories
  command: chown -R www-data:www-data /var/www/vhosts/{{ item.hostname }}/public_html
  with_items:
      hosts

# - name: Start php-fpm Service
#   service: 
#       name=php5-fpm
#       state=started
#       enabled=yes